# Generated by Django 3.2.5 on 2021-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_pricetable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdct_img', models.ImageField(blank=True, upload_to='product')),
                ('prdct_title', models.CharField(max_length=250, verbose_name='Заголовок услуги')),
                ('prdct_description', models.CharField(max_length=250, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
