# Generated by Django 3.2.5 on 2021-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20210802_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcard',
            old_name='prdct_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='prdct_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='prdct_img',
        ),
        migrations.AddField(
            model_name='productcard',
            name='img',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='Изображение услуги'),
        ),
    ]
