# Generated by Django 3.2.5 on 2021-08-03 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20210802_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Цена пакета услуг', 'verbose_name_plural': 'Цены пакетов услуг'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услуга и их цена', 'verbose_name_plural': 'Услуги и их цены'},
        ),
        migrations.AddField(
            model_name='pricecard',
            name='pc_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название пакета'),
            preserve_default=False,
        ),
    ]
