# Generated by Django 3.2.5 on 2021-07-30 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='CSS класс'),
            preserve_default=False,
        ),
    ]
